# Generated by Django 6.0.4 on 2026-04-10 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_post_id', models.BigIntegerField(verbose_name='ID du post original')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('post_type', models.CharField(max_length=10, verbose_name='Type de publication')),
                ('created_at', models.DateTimeField(verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'archivage")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_posts', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Publication archivée',
                'verbose_name_plural': 'Publications archivées',
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['-archived_at'], name='posts_archi_archive_e83396_idx')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('post_type', models.CharField(choices=[('GLOBAL', 'Globale'), ('CLASS', 'Classe'), ('PERSONAL', 'Personnel')], default='GLOBAL', max_length=10, verbose_name='Type de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('classroom', models.ForeignKey(blank=True, help_text='À remplir si le type est "Classe"', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='academic.classroom', verbose_name='Classe')),
                ('target_user', models.ForeignKey(blank=True, help_text='À remplir si le type est "Personnel"', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_posts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur cible')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='posts_post_created_183a3b_idx'), models.Index(fields=['is_active'], name='posts_post_is_acti_7bbb89_idx'), models.Index(fields=['post_type'], name='posts_post_post_ty_83ef6a_idx')],
            },
        ),
    ]
