# Generated by Django 6.0.4 on 2026-04-12 10:03

import apps.posts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.posts.models.post_media_path, verbose_name='Fichier')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('PDF', 'Document PDF'), ('VIDEO', 'Vidéo'), ('OTHER', 'Autre')], default='OTHER', max_length=10, verbose_name='Type de média')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post', verbose_name='Publication')),
            ],
            options={
                'verbose_name': 'Média de publication',
                'verbose_name_plural': 'Médias de publication',
                'ordering': ['created_at'],
            },
        ),
    ]
